[2019-04-12 09:33:12] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at D:\\xampp\\htdocs\\invalidedconvapi\\vendor\\laravel\\framework\\src\\Illuminate\\Contracts\\Queue\\QueueableEntity.php:5)
[stacktrace]
#0 {main}
"} 
[2019-04-12 09:34:14] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at D:\\xampp\\htdocs\\invalidedconvapi\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Route.php:38)
[stacktrace]
#0 {main}
"} 
[2019-04-12 09:36:08] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at D:\\xampp\\htdocs\\invalidedconvapi\\vendor\
esbot\\carbon\\src\\Carbon\\Traits\\Rounding.php:26)
[stacktrace]
#0 {main}
"} 
[2019-04-12 14:45:04] local.ERROR: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
 (SQL: select * from `conventions` where `valide` = non)  
[2019-04-12 14:45:08] local.ERROR: SQLSTATE[HY000] [2002] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
 (SQL: select * from `stages` inner join `conventions` on `stages`.`id` = `conventions`.`idStage` inner join `stages_etudiants` on `stages`.`id` = `stages_etudiants`.`idStages` inner join `etudiants` on `stages_etudiants`.`idEtudaint` = `etudiants`.`id`)  
[2019-04-12 15:00:37] local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 30 seconds exceeded at D:\\xampp\\htdocs\\invalidedconvapi\\vendor\
esbot\\carbon\\src\\Carbon\\Traits\\Date.php:497)
[stacktrace]
#0 {main}
"} 
